# Pandas for Data Engineering — A Practical Guide

This notebook demonstrates essential pandas operations for data engineering workflows, including data loading, type conversion, null handling, outlier filtering, date manipulation, feature creation, merging, and aggregation. It uses an e-commerce orders dataset (~369K rows) and a stores reference table to illustrate real-world data manipulation techniques.

### Preparing the Dataset

Before diving into analysis, we need to load the required libraries and import the raw data. This section covers importing pandas and reading the orders CSV file into a DataFrame.

In [0]:
# Import the pandas library — the primary data manipulation library in Python
import pandas as pd

In [0]:
# Load the orders dataset from the data directory
# The CSV file contains e-commerce order records with 29 columns
orders = pd.read_csv('../data/orders.csv')
orders.head()

   order_id  store_id  ...  order_metric_transit_time  order_metric_cycle_time
0  68405119      3512  ...                        NaN                      NaN
1  68405123      3512  ...                        NaN                      NaN
2  68405206      3512  ...                        NaN                      NaN
3  68405465      3401  ...                        NaN                      NaN
4  68406064      3401  ...                        NaN                      NaN

[5 rows x 29 columns]

### Data Structure Analysis

Once the data is loaded, we inspect its structure — column names, data types, null values, and duplicate rows — to understand what cleaning steps are needed.

In [0]:
# Display rows where the 'order_status' column has null values
# This helps identify missing data that may need to be handled
orders[
    orders['order_status'].isnull()
]

Empty DataFrame
Columns: [order_id, store_id, channel_id, payment_order_id, delivery_order_id, order_status, order_amount, order_delivery_fee, order_delivery_cost, order_created_hour, order_created_minute, order_created_day, order_created_month, order_created_year, order_moment_created, order_moment_accepted, order_moment_ready, order_moment_collected, order_moment_in_expedition, order_moment_delivering, order_moment_finished, order_metric_collected_time, order_metric_paused_time, order_metric_production_time, order_metric_walking_time, order_metric_expediton_speed_time, order_metric_transit_time, order_metric_cycle_time]
Index: []

In [0]:
# List all column names in the DataFrame
orders.columns

Index(['order_id', 'store_id', 'channel_id', 'payment_order_id',
       'delivery_order_id', 'order_status', 'order_amount',
       'order_delivery_fee', 'order_delivery_cost', 'order_created_hour',
       'order_created_minute', 'order_created_day', 'order_created_month',
       'order_created_year', 'order_moment_created', 'order_moment_accepted',
       'order_moment_ready', 'order_moment_collected',
       'order_moment_in_expedition', 'order_moment_delivering',
       'order_moment_delivered', 'order_moment_finished',
       'order_metric_collected_time', 'order_metric_paused_time',
       'order_metric_production_time', 'order_metric_walking_time',
       'order_metric_expediton_speed_time', 'order_metric_transit_time',
       'order_metric_cycle_time'],
      dtype='object')

In [0]:
# Drop the 'order_moment_delivered' column
# axis=1 indicates column-level operation (axis=0 would be row-level)
# inplace=True modifies the DataFrame in place without returning a copy
orders.drop('order_moment_delivered', axis=1, inplace=True)

In [0]:
# Count unique values in the 'order_status' column
# Equivalent to SQL: SELECT order_status, COUNT(*) FROM orders GROUP BY order_status
orders['order_status'].value_counts()

order_status
FINISHED    352020
CANCELED     16979
Name: count, dtype: int64

In [0]:
# The 'dtype' property shows the data type of a Series
# The 'astype()' method converts a column to a different data type
print(f"Before: {orders['order_id'].dtype}")
orders['order_id'] = orders['order_id'].astype(int)
print(f"After: {orders['order_id'].dtype}")

In [0]:
# Convert 'order_amount' from string to float for numeric operations
print(f"Before: {orders['order_amount'].dtype}")
orders['order_amount'] = orders['order_amount'].astype(float)
print(f"After: {orders['order_amount'].dtype}")

0          62.7
1          62.7
2         115.5
3          55.9
4          37.9
          ...
368994     28.0
368995     49.0
368996    128.7
368997    127.4
368998    104.7
Name: order_amount, Length: 368999, dtype: float64

In [0]:
# Remove duplicate rows based on the 'order_id' column
# The 'subset' parameter specifies which columns to use for deduplication
orders.drop_duplicates(subset=['order_id'])

        order_id store_id  ... order_metric_transit_time order_metric_cycle_time
0       68405119     3512  ...                      None                    None
1       68405123     3512  ...                      None                    None
2       68405206     3512  ...                      None                    None
3       68405465     3401  ...                      None                    None
4       68406064     3401  ...                      None                    None
...          ...      ...  ...                       ...                     ...
368994  93139806     2074  ...                     23.42                   68.53
368995  93139809      707  ...                     20.67                    57.6
368996  93139813      631  ...                     17.55                   65.65
368997  93139814      631  ...                     13.17                   45.32
368998  93139817      236  ...                     21.12                   47.72

[368999 rows x 29 columns]

In [0]:
# Convert 'order_delivery_cost' from string to float
orders['order_delivery_cost'] = orders['order_delivery_cost'].astype(float)

In [0]:
# Fill null values in 'order_delivery_cost' with the column mean (rounded to 2 decimal places)
# The fillna() method replaces NaN values with the specified value
orders['order_delivery_cost'] = orders['order_delivery_cost'].fillna(round(orders['order_delivery_cost'].mean(), 2))

In [0]:
# Replace 'CANCELED' with 'CANCELADO' in the 'order_status' column
# The loc[] accessor allows label-based selection and assignment
orders.loc[
    (orders['order_status'] == 'CANCELED'), 'order_status'
] = 'CANCELADO'

### Anomalies & Outliers

Statistical summary and outlier detection help identify data quality issues. We use `describe()` to get distribution statistics and filter out extreme values that could skew analysis.

In [0]:
# Configure pandas to display float values with 2 decimal places
pd.set_option('display.float_format', '{:.2f}'.format)

In [0]:
# Generate descriptive statistics for the 'order_amount' column
# Shows count, mean, std, min, quartiles, and max
orders['order_amount'].describe()

count    368999.00
mean        105.15
std        2953.11
min           0.00
25%          39.90
50%          71.60
75%         121.90
max     1788306.11
Name: order_amount, dtype: float64

In [0]:
# Filter out outlier orders with amount >= 1000
# These extreme values can distort aggregations and analysis
orders = orders[
    (orders['order_amount'] < 1000)    
]

In [0]:
# Re-check the descriptive statistics after removing outliers
orders['order_amount'].describe()

count   368192.00
mean        95.42
std         85.51
min          0.00
25%         39.90
50%         71.40
75%        121.40
max        999.99
Name: order_amount, dtype: float64

### Date Manipulation

Working with dates is essential for time-based analysis. We convert string timestamps to datetime objects and extract date components for grouping and filtering.

In [0]:
# Convert 'order_moment_created' to datetime, then extract just the date portion
# pd.to_datetime() parses string timestamps into datetime objects
# .dt.date extracts the date component (YYYY-MM-DD), discarding the time
orders['order_moment_created_date'] = pd.to_datetime(orders['order_moment_created']).dt.date

/home/spark-c3d67c9d-6619-4f3a-b888-54/.ipykernel/64/command-5117453766091745-734366287:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders['order_moment_created_date'] = pd.to_datetime(orders['order_moment_created']).dt.date

In [0]:
# Verify that the new date column was added to the DataFrame
orders.columns

Index(['order_id', 'store_id', 'channel_id', 'payment_order_id',
       'delivery_order_id', 'order_status', 'order_amount',
       'order_delivery_fee', 'order_delivery_cost', 'order_created_hour',
       'order_created_minute', 'order_created_day', 'order_created_month',
       'order_created_year', 'order_moment_created', 'order_moment_accepted',
       'order_moment_ready', 'order_moment_collected',
       'order_moment_in_expedition', 'order_moment_delivering',
       'order_moment_delivered', 'order_moment_finished',
       'order_metric_collected_time', 'order_metric_paused_time',
       'order_metric_production_time', 'order_metric_walking_time',
       'order_metric_expediton_speed_time', 'order_metric_transit_time',
       'order_metric_cycle_time', 'order_moment_created_date'],
      dtype='object')

In [0]:
# Display the newly created date column
orders['order_moment_created_date']

0         2021-01-01
1         2021-01-01
2         2021-01-01
3         2021-01-01
4         2021-01-01
             ...
368994    2021-04-30
368995    2021-04-30
368996    2021-04-30
368997    2021-04-30
368998    2021-04-30
Name: order_moment_created_date, Length: 368192, dtype: object

### Creating New Columns

Feature engineering — creating new columns from existing ones — is a core data preparation step. Here we combine multiple metric columns to derive a lead time metric.

In [0]:
# Display a summary of the DataFrame including column types and non-null counts
orders.info()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-5117453766091749>, line 1
----> 1 orders.info(nulls=True)

TypeError: DataFrame.info() got an unexpected keyword argument 'nulls'

In [0]:
# Convert time metric columns from string to float for arithmetic operations
orders['order_metric_collected_time'] = orders['order_metric_collected_time'].astype(float)
orders['order_metric_production_time'] = orders['order_metric_production_time'].astype(float)

In [0]:
# Create a new column 'lead_time_product' by summing collection and production times
# This represents the total time from order collection to production completion
orders['lead_time_product'] = orders['order_metric_collected_time'] + orders['order_metric_production_time']
orders['lead_time_product'].describe()

count   316891.00
mean        29.20
std        218.72
min          0.10
25%         11.35
50%         17.20
75%         23.96
max      85667.05
Name: lead_time_product, dtype: float64

In [0]:
# Filter orders where lead time exceeds 1000 (potential anomalies)
orders[
    (orders['lead_time_product']) > 1000
]

        order_id store_id  ... order_moment_created_date lead_time_product
8       68410055     2181  ...                2021-01-01           2397.88
1432    68617646     3535  ...                2021-01-02           2982.50
2382    68682346     1608  ...                2021-01-02           3023.03
5629    68950673      657  ...                2021-01-03           1209.44
7075    69106464     1679  ...                2021-01-04           7343.79
...          ...      ...  ...                       ...               ...
363903  93104891     3322  ...                2021-04-29           1455.82
364558  93111738     3322  ...                2021-04-29           1321.35
365081  93115681     1015  ...                2021-04-29           1205.41
366948  93129846     2110  ...                2021-04-30           1487.26
368223  93137109     2013  ...                2021-04-30           1012.77

[1271 rows x 31 columns]

### Grouping and Selection

Aggregating data by groups is fundamental for reporting and analysis. We use `groupby()` with `agg()` — similar to SQL's `GROUP BY` — to summarize order amounts by date and store.

In [0]:
# Group orders by date and store, then sum the order amounts
# Equivalent to SQL: SELECT order_moment_created_date, store_id, SUM(order_amount)
#                  FROM orders GROUP BY order_moment_created_date, store_id
orders.groupby(['order_moment_created_date', 'store_id']).agg({'order_amount':'sum'}).reset_index()

      order_moment_created_date store_id  order_amount
0                    2021-01-01     1016        731.70
1                    2021-01-01     1018        457.48
2                    2021-01-01     1037       7683.80
3                    2021-01-01     1056        165.40
4                    2021-01-01     1057       3803.50
...                         ...      ...           ...
33537                2021-04-30      983        569.67
33538                2021-04-30      989        109.90
33539                2021-04-30       99        359.50
33540                2021-04-30      998        158.00
33541                2021-04-30      999         59.90

[33542 rows x 3 columns]

In [0]:
# Load the stores reference dataset
# encoding='latin-1' is used because the file contains non-UTF-8 characters (Portuguese accents)
stores = pd.read_csv('../data/stores.csv', encoding='latin-1')
stores.head()

   store_id  hub_id  ... store_latitude store_longitude
0         3       2  ...            NaN             NaN
1         6       3  ...         -30.04          -51.20
2         8       3  ...         -30.04          -51.20
3        53       8  ...         -22.92          -43.23
4        54       8  ...         -22.92          -43.23

[5 rows x 7 columns]

In [0]:
# Extract store_id and store_name into a new DataFrame for joining
stores_name = stores[['store_id', 'store_name']].copy()

In [0]:
# Merge orders with store names using a left join on 'store_id'
# This enriches the orders data with human-readable store names
orders_store = orders.merge(stores_name, how='left', on='store_id')
orders_store.head()

   order_id store_id  ... lead_time_product     store_name
0  68405119     3512  ...               NaN  GOI SIPIMUSU
1  68405123     3512  ...               NaN  GOI SIPIMUSU
2  68405206     3512  ...               NaN  GOI SIPIMUSU
3  68405465     3401  ...               NaN        FRUEOU
4  68406064     3401  ...               NaN        FRUEOU

[5 rows x 32 columns]

In [0]:
# Group by date and store name, then sum order amounts
# This produces a daily revenue summary per store
order_amount_stores = orders_store.groupby(['order_moment_created_date', 'store_name']).agg({'order_amount':'sum'}).reset_index()

In [0]:
# Export the aggregated result to a CSV file in the data directory
# index=False prevents pandas from writing the row index as a column
order_amount_stores.to_csv('../data/order_amount_stores.csv', index=False)

In [0]:
# Display the final aggregated DataFrame
order_amount_stores.head()

order_moment_created_date,store_name,order_amount
2021-01-01,AR PAZZI,745.4
2021-01-01,AR TRAMUO,74.5
2021-01-01,ARE TRAMUO,125.0
2021-01-01,CILAFIRMAI CIOLA,1090.12
2021-01-01,CIRIROI U CAI,1009.5
2021-01-01,CISI DA PILIP,25.5
2021-01-01,CISI DA URPIOU,52.1
2021-01-01,CISI PIUEUEMI,123.5
2021-01-01,CZALLA PUIMS,399.98
2021-01-01,EAVAMI FIGOI,2109.1
2021-01-01,FIPRACI EA MPECILIMU,172.0
2021-01-01,FRUEOU,93.8
2021-01-01,GARIOLIS,216.31
2021-01-01,GIMA,485.6
2021-01-01,GOI SIPIMUSU,595.7
2021-01-01,GRIME CRU,214.8
2021-01-01,GUIAPUCI PURGUR,200.0
2021-01-01,GUIRGUES,637.8
2021-01-01,ICI EU SIVEMI,457.48
2021-01-01,IMLAIZA,83.6
2021-01-01,IPALUPAES,1592.1000000000001
2021-01-01,IPUPIEMAI,8083.75
2021-01-01,IUMPICA,63009.7
2021-01-01,LILI CISRUMACS,394.8
2021-01-01,LIS RUS,82.0
2021-01-01,LU PUMAM RICIRIMS,80.0
2021-01-01,MATATA,110.5
2021-01-01,MIUMSAU,46.7
2021-01-01,MOIRI MPECILIMU PIR,29.8
2021-01-01,MRIMUIRAI,322.0
2021-01-01,MRUS GIROUS,139.0
2021-01-01,MU PURGAR,638.0
2021-01-01,MZU PIUI,170.5
2021-01-01,MZU PLICA PAF,40.0
2021-01-01,MZU SMUIG FICMIRO,89.83
2021-01-01,MZU SUACU LIP,68.22
2021-01-01,PAPA SUCIS,188.2
2021-01-01,PASSIMA,95.0
2021-01-01,PAZZI PIRPACO,468.0
2021-01-01,PAZZI ZUM,3518.9
2021-01-01,PEC PILIS,20.0
2021-01-01,PIAMUARIS,244.4
2021-01-01,PIAMUARIS CIFO,128.0
2021-01-01,PIARO,1410.25
2021-01-01,PIARU,110.9
2021-01-01,PIGUE PIPACO,6403.5
2021-01-01,PILIOU RAS,2709.2999999999997
2021-01-01,PILITAMZI,77.35
2021-01-01,PIPS,731.6999999999999
2021-01-01,PIZ RUSMIURIMA,214.0
2021-01-01,PUGOIE,70.5
2021-01-01,PULGAIM SIOLLU,30.9
2021-01-01,RASMUR S,1229.0
2021-01-01,REMFRUMIS,65.0
2021-01-01,RIOZ,165.4
2021-01-01,RIRAI CISAMZI,48.5
2021-01-01,RIRURPIS,208.33999999999997
2021-01-01,RIVUMOI MRIMUIRAI,76.8
2021-01-01,RO PISMUAS,219.4
2021-01-01,RUA DA RIMU,63.9
2021-01-01,RUSMIURIMA RIRIOU,32.0
2021-01-01,SIZMUO RICAUMS,20.0
2021-01-01,SUPSIO,34.2
2021-01-01,SUPUR GRALA,37.9
2021-01-01,SUSZA OIRI,67.8
2021-01-01,TRAZ LOURA RIRMAM,901.0
2021-01-01,USARULI DA SUA,168.0
2021-01-01,VUZPI,125.6
2021-01-01,VUZPI PAZZIS,19.9
2021-01-01,ZIM M MUMEUR,946.3
2021-01-01,ZIRIE,34.9
2021-01-01,ZIVIMUI,178.7
2021-01-02,AR PAZZI,537.4
2021-01-02,ARE TRAMUO,1226.7
2021-01-02,CICIU SZIS,95.8
2021-01-02,CILAFIRMAI CIOLA,872.74
2021-01-02,CIMUAMI PUIMISURI,466.1
2021-01-02,CIPIMI PURGUR,187.0
2021-01-02,CIRIOURI PURGAR,1525.3
2021-01-02,CIRIROI U CAI,502.7
2021-01-02,CISI DA PILIP,91.5
2021-01-02,CISI DA POI EU QUASI,289.0
2021-01-02,CISI DA URPIOU,158.9
2021-01-02,CISI PILIME,42.5
2021-01-02,CISI PIUEUEMI,625.4
2021-01-02,CRUPULICOS,43.8
2021-01-02,CZALLA PUIMS,259.98
2021-01-02,CZALLA PUIMS LISI,259.98
2021-01-02,EA CUMUI,226.6
2021-01-02,EAVAMI FIGOI,1672.8999999999999
2021-01-02,EURECA,75.0
2021-01-02,FAIARUMUI,547.9
2021-01-02,FIPRACI EA MPECILIMU,113.5
2021-01-02,FRUEOU,257.5
2021-01-02,FRUG FRIZUM,32.0
2021-01-02,GARIOLIS,817.35
2021-01-02,GIMA,1212.2
2021-01-02,GOI SIPIMUSU,605.5
2021-01-02,GUIAPUCI PURGUR,428.05
2021-01-02,GUIRGUES,325.2
2021-01-02,GULIMURAI RE,491.0
2021-01-02,GUMOUA E ISIM,1622.4
2021-01-02,I CISI DA PAMPE,331.9
2021-01-02,ICI EU SIVEMI,155.89
2021-01-02,IEPISMI,810.03
2021-01-02,ILAVI,109.6
2021-01-02,IMIUGA VUGIMI,86.7
2021-01-02,IMLAIZA,0.0
2021-01-02,IPALUPAES,3909.5
2021-01-02,IPUPIEMAI,18289.0
2021-01-02,ISIM,2000.97
2021-01-02,ISIM O RIRARIRA,325.2
2021-01-02,ISZUI,139.9
2021-01-02,IUMPICA,104376.71
2021-01-02,LIS URPIMIOUS,120.0
2021-01-02,LUCITA,945.4000000000001
2021-01-02,LUPIMUIM,2082.8
2021-01-02,LUVAES,764.78
2021-01-02,MATATA,214.0
2021-01-02,MICI PULA,645.3
2021-01-02,MIMAMI SAMU VAMUIGU,276.0
2021-01-02,MOIRI MPECILIMU PIR,149.79999999999998
2021-01-02,MRIMUIRAI,110.0
2021-01-02,MRUS GIROUS,437.0
2021-01-02,MU PURGAR,1209.0
2021-01-02,MUMRIFAM,507.4
2021-01-02,MUMUO PIVIRAIM,77.2
2021-01-02,MZU PIUI,205.8
2021-01-02,MZU PLICA PAF,140.8
2021-01-02,MZU SMUIG FICMIRO,77.8
2021-01-02,MZU SUACU LIP,72.8
2021-01-02,OIGIPUARO,871.0
2021-01-02,OU SALVI,59.0
2021-01-02,PAI RUMOU,775.5699999999999
2021-01-02,PALLO MZU GRALA,2304.0
2021-01-02,PALLO PURGAR,241.5
2021-01-02,PAPA SUCIS,10394.1
2021-01-02,PAZZI PIRPACO,1613.0
2021-01-02,PAZZI ROIE MIPILAPACO,201.0
2021-01-02,PAZZI ZUM,6006.74
2021-01-02,PEC PILIS,76.0
2021-01-02,PF PIR FIVIR,542.6
2021-01-02,PIAMUARIS,29.9
2021-01-02,PIAMUARIS CIFO,346.5
2021-01-02,PIARO,3418.66
2021-01-02,PIARU,227.79000000000002
2021-01-02,PIGUE PIPACO,2696.9
2021-01-02,PILIOU RAS,2854.61
2021-01-02,PILITAMZI,249.85
2021-01-02,PIMGUCIS DA VIVA,1143.8999999999999
2021-01-02,PIMRIMA,1218.3
2021-01-02,PIPRU SUIM,3838.96
2021-01-02,PIPS,66.7
2021-01-02,PIRAGUAM,71.28
2021-01-02,PIRMI DA SIPIR,256.0
2021-01-02,PIRPALA,349.8
2021-01-02,PIULIMGURAU CIRAICI,266.1
2021-01-02,PIZ RUSMIURIMA,153.0
2021-01-02,PRARIZZAI,119.0
2021-01-02,PRIMZURS RUSMIURIMA U PAZZIRAI,299.1
2021-01-02,PRISEMCICIU,40.0
2021-01-02,PRISMAURAI,185.28
2021-01-02,PUCIRAMI,433.6
2021-01-02,PUGOIE,109.0
2021-01-02,PULGAIM SIOLLU,47.8
2021-01-02,PUMGUA,543.5
2021-01-02,PUPALU RAS,44.5
2021-01-02,PUPALU RAS MUI,160.0
2021-01-02,RASMUR S,2783.0
2021-01-02,RC OUMILEES,4957.7
2021-01-02,RE GULIMURAI,52.0
2021-01-02,RIARI SIARI,180.0
2021-01-02,RIC IME CZASU,256.0
2021-01-02,RIMAI EU TRAPRISCI,1680.7
2021-01-02,RIOZ,188.3
2021-01-02,RIRAI CISAMZI,385.9
2021-01-02,RIRURPIS,731.84
2021-01-02,RISA PUM,105.60000000000001
2021-01-02,RIUSSUCIGU,208.10000000000002
2021-01-02,RIVUMOI MRIMUIRAI,265.3
2021-01-02,RO PISMUAS,3675.25
2021-01-02,SALITO,1193.19
2021-01-02,SIRVUMU AMILAI,788.7
2021-01-02,SIZMUO RICAUMS,2742.0
2021-01-02,SPILUMI,2655.71
2021-01-02,SR MIPICIRAI,117.0
2021-01-02,SR SIGIRIMI,6016.5
2021-01-02,SUCOI LIMTRAS,121.4
2021-01-02,SUMIR SIMMPE,34.9
2021-01-02,SUPSIO,1565.53
2021-01-02,SUPUR GRALA,50.4
2021-01-02,SUSM GRALA,241.5
2021-01-02,SUSZAIGA,2785.2
2021-01-02,TRAF VURGO,50.6
2021-01-02,TRAZ LOURA RIRMAM,740.0
2021-01-02,UMALACISI,39.98
2021-01-02,USARULI DA SUA,51.45
2021-01-02,USPUMUI CIRAICI,134.75
2021-01-02,VALLUES CIOLA E CIGU CIE,89.2
2021-01-02,VIRIMOU,282.54
2021-01-02,VUG U LUV,758.0
2021-01-02,VUG UP,537.0
2021-01-02,VUZPI,111.8
2021-01-02,VUZPI PAZZIS,185.70000000000002
2021-01-02,ZIM M MUMEUR,1575.4
2021-01-02,ZIM ME MUMEUR,655.1
2021-01-02,ZIMI ZUM,56.0
2021-01-02,ZIMRPI,339.72
2021-01-02,ZIRIE,86.6
2021-01-02,ZIVIMUI,148.0
2021-01-02,ZURAMG CIMUMU,279.98
2021-01-03,AR PAZZI,470.20000000000005
2021-01-03,AR TRAMUO,155.0
2021-01-03,ARE TRAMUO,1193.0
2021-01-03,ASASS,46.0
2021-01-03,CICIU SZIS,339.4
2021-01-03,CILAFIRMAI CIOLA,979.1800000000001
2021-01-03,CIMUAMI PUIMISURI,738.7
2021-01-03,CIOLAMISM,15.0
2021-01-03,CIPIMI PURGUR,299.0
2021-01-03,CIRIOURI PURGAR,191.2
2021-01-03,CIRIROI U CAI,1427.6
2021-01-03,CISI DA POI EU QUASI,104.5
2021-01-03,CISI DA URPIOU,33.2
2021-01-03,CISI PILIME,32.0
2021-01-03,CISI PIUEUEMI,887.39
2021-01-03,CRICS,179.0
2021-01-03,CRUPULICOS,323.1
2021-01-03,EA CUMUI,1226.1
2021-01-03,EAVAMI FIGOI,2622.4
2021-01-03,EU POI MI ILRIMI,112.9
2021-01-03,EULARAI MRIPACIA,175.9
2021-01-03,FAIARUMUI,239.5
2021-01-03,FIPRACI EA MPECILIMU,26.0
2021-01-03,GARIOLIS,1812.59
2021-01-03,GIMA,2202.5
2021-01-03,GOI SIPIMUSU,65.2
2021-01-03,GUIAPUCI PURGUR,34.0
2021-01-03,GUIRGUES,779.91
2021-01-03,GULIMURAI RE,491.0
2021-01-03,GUMOUA,213.0
2021-01-03,GUMOUA E ISIM,2385.29
2021-01-03,I CISI DA PAMPE,74.65
2021-01-03,IASZPILITA,94.0
2021-01-03,ICI EU SIVEMI,374.92
2021-01-03,IEPISMI,1334.6299999999999
2021-01-03,IGUAI VUMURAMIRAI,109.0
2021-01-03,ILAVI,585.3
2021-01-03,IMIUGA VUGIMI,175.5
2021-01-03,IPA EMUOU,164.97
2021-01-03,IPALUPAES,3782.4
2021-01-03,IPUPIEMAI,29254.0
2021-01-03,ISIM,1541.97
2021-01-03,ISZUI,259.8
2021-01-03,IUMPICA,139610.33
2021-01-03,LIS RUS,317.0
2021-01-03,LIS URPIMIOUS,101.0
2021-01-03,LUCITA,1054.95
2021-01-03,LUPIMUIM,2382.42
2021-01-03,LUVAES,352.25
2021-01-03,MATATA,26.0
2021-01-03,MICI PULA,570.0
2021-01-03,MIMAMI SAMU VAMUIGU,173.0
2021-01-03,MIZPIZ,40.2
2021-01-03,MOIRI MPECILIMU PIR,45.4
2021-01-03,MPECILIMRIS CAOUEU PIASI,121.35
2021-01-03,MRIMUIRAI,56.0
2021-01-03,MRUS GIROUS,304.0
2021-01-03,MU PURGAR,1462.0
2021-01-03,MUMRIFAM,913.2
2021-01-03,MZU PIUI,324.8
2021-01-03,MZU PLICA PAF,127.30000000000001
2021-01-03,MZU SMUIG FICMIRO,146.31
2021-01-03,OIGIPUARO,598.0
2021-01-03,OU SALVI,154.0
2021-01-03,PALLO MZU GRALA,3271.1
2021-01-03,PALLO PURGAR,155.39999999999998
2021-01-03,PAPA SUCIS,13067.7
2021-01-03,PASSIMA,76.0
2021-01-03,PAZZI PIRPACO,2155.4
2021-01-03,PAZZI ZUM,5967.72
2021-01-03,PIAMUARIS,88.9
2021-01-03,PIAMUARIS CIFO,538.9
2021-01-03,PIARO,2410.54
2021-01-03,PIGUE PIPACO,3225.9
2021-01-03,PILIOU RAS,3932.62
2021-01-03,PILITAMZI,66.35
2021-01-03,PIMGUCIS DA VIVA,333.7
2021-01-03,PIMRIMA,1333.8999999999999
2021-01-03,PIPRU SUIM,3661.8199999999997
2021-01-03,PIPS,199.0
2021-01-03,PIRMI DA SIPIR,395.8
2021-01-03,PIULIMGURAU CIRAICI,301.4
2021-01-03,PIZ RUSMIURIMA,90.0
2021-01-03,PRARIZZAI,172.3
2021-01-03,PRIMZURS RUSMIURIMA U PAZZIRAI,1118.8
2021-01-03,PRISMAURAI,135.57
2021-01-03,PUCIRAMI,254.5
2021-01-03,PULGAIM SIOLLU,32.9
2021-01-03,PUMGUA,225.0
2021-01-03,PUPALU RAS,296.0
2021-01-03,PUPALU RAS MUI,82.5
2021-01-03,RA VACAI EUSEU I AMACAI,27.5
2021-01-03,RASMUR S,2415.2
2021-01-03,RC OUMILEES,5885.0
2021-01-03,RE GULIMURAI,141.0
2021-01-03,REMFRUMIS,130.0
2021-01-03,RIARI SIARI,556.0
2021-01-03,RIC IME CZASU,44.8
2021-01-03,RIGAC FAM,179.99
2021-01-03,RIGU I CIGU,405.9
2021-01-03,RIMAI EU TRAPRISCI,1142.3
2021-01-03,RIRAI CISAMZI,306.0
2021-01-03,RIRURPIS,1298.99
2021-01-03,RISA PUM,211.8
2021-01-03,RIUSSUCIGU,328.2
2021-01-03,RIVUMOI MRIMUIRAI,182.7
2021-01-03,RO PISMUAS,3047.01
2021-01-03,RUA DA RIMU,74.8
2021-01-03,RUSMIURIMA RIRIOU,67.0
2021-01-03,SIRVUMU AMILAI,473.3
2021-01-03,SIZMUO RICAUMS,5732.8
2021-01-03,SPILUMI,3316.93
2021-01-03,SR SIGIRIMI,6184.02
2021-01-03,SUMIR SIMMPE,294.51
2021-01-03,SUPSIO,2624.2
2021-01-03,SUPUR GRALA,343.59999999999997
2021-01-03,SUSZAIGA,5112.2
2021-01-03,TRAZ LOURA RIRMAM,1236.0
2021-01-03,USARULI DA SUA,57.65
2021-01-03,USPUMUI CIRAICI,454.57000000000005
2021-01-03,VALLUES CIOLA E CIGU CIE,71.2
2021-01-03,VUG U LUV,2322.0
2021-01-03,VUG UP,1205.0
2021-01-03,VUZPI,224.60000000000002
2021-01-03,VUZPI PAZZIS,349.6
2021-01-03,ZIM M MUMEUR,841.53
2021-01-03,ZIM ME MUMEUR,242.10000000000002
2021-01-03,ZIMRPI,0.0
2021-01-03,ZIRIE,146.2
2021-01-03,ZIVIMUI,35.5
2021-01-04,ACA PRISSURAU,256.0
2021-01-04,AIEMAMIMU IU PRUSEM,366.8
2021-01-04,AR PAZZI,329.6
2021-01-04,AR TRAMUO,150.6
2021-01-04,ARE TRAMUO,533.2
2021-01-04,CAIRIR PIPO,50.0
2021-01-04,CICIU SZIS,56.150000000000006
2021-01-04,CILAFIRMAI CIOLA,347.17
2021-01-04,CIPIMI PURGUR,60.0
2021-01-04,CIRACIOU,1196.78
2021-01-04,CIRIOURI PURGAR,593.8
2021-01-04,CIRIROI U CAI,330.1
2021-01-04,CISI DA PILIP,35.0
2021-01-04,CISI DA POI EU QUASI,52.5
2021-01-04,CISI PIUEUEMI,179.0
2021-01-04,CLUPU RULASSI,249.9
2021-01-04,CRUPULICOS,177.2
2021-01-04,CUMOIARAS,99.9
2021-01-04,CZALLA PUIMS,679.96
2021-01-04,CZALLA PUIMS LISI,349.98
2021-01-04,EA CUMUI,56.0
2021-01-04,EAVAMI FIGOI,2464.0
2021-01-04,ECILUMI MI LISI FASACIO PASCIAMO,135.4
2021-01-04,EULARAI MRIPACIA,266.1
2021-01-04,EURECA,37.8
2021-01-04,FAIARUMUI,131.6
2021-01-04,FIPRACI EA MPECILIMU,73.0
2021-01-04,FRUEOU,435.3
2021-01-04,FRUG FRIZUM,102.0
2021-01-04,GARIOLIS,253.62
2021-01-04,GARPI,114.8
2021-01-04,GIMA,859.6
2021-01-04,GOI SIPIMUSU,359.8
2021-01-04,GRIME CRU,534.81
2021-01-04,GRIMEVASAIM,165.0
2021-01-04,GUIAPUCI PURGUR,151.0
2021-01-04,GUIRGUES,47.8
2021-01-04,GULIMI PIRULA,55.0
2021-01-04,GULIMURAI RE,258.0
2021-01-04,GUMOUA E ISIM,1302.18
2021-01-04,I CISI DA PAMPE,933.63
2021-01-04,IASZPILITA,34.0
2021-01-04,ICI EU SIVEMI,238.48000000000002
2021-01-04,IEPISMI,774.34
2021-01-04,ILAVI,208.52999999999997
2021-01-04,IMIUGA VUGIMI,87.8
2021-01-04,IPALUPAES,3315.0
2021-01-04,IPIQA,844.0
2021-01-04,IPUPIEMAI,10731.1
2021-01-04,IRIR OIS PUOUMIS,123.26
2021-01-04,ISIM,1428.74
2021-01-04,ISIM O RIRARIRA,580.3
2021-01-04,IUMPICA,49396.5
2021-01-04,LIEMAMIMU IU PRUSEM,100.9
2021-01-04,LILI CISRUMACS,99.2
2021-01-04,LIS RUS,139.0
2021-01-04,LIS URPIMIOUS,196.0
2021-01-04,LUCITA,1040.85
2021-01-04,LUPIMUIM,2190.69
2021-01-04,LUVA S,359.9
2021-01-04,LUVAES,199.9
2021-01-04,META EASSU PURUMACU,35.9
2021-01-04,MICI PULA,251.0
2021-01-04,MRIMUIRAI,277.0
2021-01-04,MU PURGAR,192.0
2021-01-04,MUMRIFAM,1754.0
2021-01-04,MUMUO PIVIRAIM,88.30000000000001
2021-01-04,MURPURI OUS GURAIS,1274.61
2021-01-04,MZU PIUI,137.3
2021-01-04,MZU PLICA PAF,82.0
2021-01-04,MZU SMUIG FICMIRO,125.6
2021-01-04,MZU SUACU LIP,55.730000000000004
2021-01-04,OIGIPUARO,232.0
2021-01-04,PAI RUMOU,345.24
2021-01-04,PALLO MZU GRALA,1834.3
2021-01-04,PALLO PURGAR,48.6
2021-01-04,PAPA SUCIS,9609.6
2021-01-04,PASCIAMO,58.8
2021-01-04,PASCIAMU,72.5
2021-01-04,PASSIMA,93.0
2021-01-04,PAZZI PIRPACO,578.0
2021-01-04,PAZZI ZUM,3874.76
2021-01-04,PEC PILIS,28.9
2021-01-04,PEUIM GAMTRAM,256.09999999999997
2021-01-04,PF PIR FIVIR,1081.5
2021-01-04,PIARO,1820.63
2021-01-04,PIARU,284.6
2021-01-04,PIGUE PIPACO,4718.099999999999
2021-01-04,PILIOU RAS,2310.8199999999997
2021-01-04,PILITAMZI,34.25
2021-01-04,PIMGUCIS DA VIVA,1463.8999999999999
2021-01-04,PIMOURUA,38.0
2021-01-04,PIMRIMA,952.8
2021-01-04,PIPRU SUIM,1789.88
2021-01-04,PIPS,251.0
2021-01-04,PIRMI DA SIPIR,472.3
2021-01-04,PIRPALA,157.2
2021-01-04,PIZ RUSMIURIMA,267.0
2021-01-04,PRIMIUVI,84.0
2021-01-04,PRIMZURS RUSMIURIMA U PAZZIRAI,303.5
2021-01-04,PRISMAURAI,49.99
2021-01-04,PUCIRAMI,167.0
2021-01-04,PUGOIE,84.0
2021-01-04,PUGUM,1843.8
2021-01-04,PUMGUA,143.5
2021-01-04,PUPALU RAS,80.5
2021-01-04,PUPALU RAS MUI,187.0
2021-01-04,PUPALUGALA,119.91999999999999
2021-01-04,RA VACAI EUSEU I AMACAI,43.75
2021-01-04,RASMUR S,2403.0
2021-01-04,RC OUMILEES,3752.4
2021-01-04,RIARI SIARI,119.0
2021-01-04,RIC IME CZASU,244.1
2021-01-04,RIGU I CIGU,154.6
2021-01-04,RIMAI EU TRAPRISCI,1077.7
2021-01-04,RIRAI CISAMZI,169.5
2021-01-04,RIRG LISUR PURSIMILAMO,115.0
2021-01-04,RIRURPIS,1711.9099999999999
2021-01-04,RISIRA,569.5
2021-01-04,RIUSSUCIGU,157.4
2021-01-04,RIVUMOI MRIMUIRAI,534.1
2021-01-04,RO PISMUAS,1220.1
2021-01-04,ROICIPIP,274.0
2021-01-04,RUA DA RIMU,21.0
2021-01-04,RUSU,703.61
2021-01-04,SALITO,1843.8600000000001
2021-01-04,SIRLE MUMUAS,249.9
2021-01-04,SIRVUMU AMILAI,198.1
2021-01-04,SIZMUO RICAUMS,1663.2
2021-01-04,SPILUMI,2233.79
2021-01-04,SR MIPICIRAI,60.5
2021-01-04,SR SIGIRIMI,4311.5
2021-01-04,SUCOI LIMTRAS,22.4
2021-01-04,SUMIR SIMMPE,137.39999999999998
2021-01-04,SUPSIO,2648.55
2021-01-04,SUPUR GRALA,60.4
2021-01-04,SUSM GRALA,37.9
2021-01-04,SUSZAIGA,2442.7
2021-01-04,TRAZ LOURA RIRMAM,69.0
2021-01-04,USIFLUS,279.9
2021-01-04,USMIMOI RS,51.8
2021-01-04,USPUMUI CIRAICI,445.7
2021-01-04,VIRIMOU,687.02
2021-01-04,VUG U LUV,991.0
2021-01-04,VUG UP,328.5
2021-01-04,VUZPI,240.8
2021-01-04,VUZPI PAZZIS,63.4
2021-01-04,ZIM M MUMEUR,1170.7
2021-01-04,ZIM ME MUMEUR,275.4
2021-01-04,ZIRIE,119.5
2021-01-04,ZURAMG GAES,49.99
2021-01-04,�RPIR PILMACI,119.9
2021-01-05,ACA PRISSURAU,533.0
2021-01-05,AIEMAMIMU IU PRUSEM,70.7
2021-01-05,AMUARASSARA,278.0
2021-01-05,AR PAZZI,244.2
2021-01-05,AR TRAMUO,544.9
2021-01-05,ARE TRAMUO,761.6
2021-01-05,ASASS,66.0
2021-01-05,CICIU SZIS,404.8
2021-01-05,CILAFIRMAI CIOLA,432.29
2021-01-05,CIMUAMI PUIMISURI,1067.0
2021-01-05,CIRACIOU,883.85
2021-01-05,CIRILAMI SILUS,46.0
2021-01-05,CIRIOURI PURGAR,383.1
2021-01-05,CIRIROI U CAI,259.2
2021-01-05,CISI DA PILIP,52.0
2021-01-05,CISI DA URPIOU,123.89999999999999
2021-01-05,CISI PILIME,62.8
2021-01-05,CISI PIUEUEMI,296.2
2021-01-05,CLUPU RULASSI,179.9
2021-01-05,CRUPULICOS,84.8
2021-01-05,CZALLA PUIMS,239.98
2021-01-05,CZALLA PUIMS LISI,299.98
2021-01-05,EA CUMUI,39.9
2021-01-05,EAVAMI FIGOI,2264.1
2021-01-05,EUCI SGAM,189.05
2021-01-05,EULARAI MRIPACIA,594.8
2021-01-05,EURECA,179.2
2021-01-05,FAIARUMUI,39.9
2021-01-05,FAM RIRGUM,314.96000000000004
2021-01-05,FIPRACI EA MPECILIMU,46.0
2021-01-05,FRUEOU,143.8
2021-01-05,FRUG FRIZUM,140.0
2021-01-05,GARIOLIS,444.2
2021-01-05,GIMA,995.91
2021-01-05,GOI SIPIMUSU,288.4
2021-01-05,GRIME CRU,902.06
2021-01-05,GRIME CRU AMIARO CIRUSI,99.9
2021-01-05,GUIAPUCI PURGUR,62.1
2021-01-05,GUIRGUES,200.1
2021-01-05,GULIMI PIRULA,85.0
2021-01-05,GULIMURAI RE,77.0
2021-01-05,GUMOUA E ISIM,1377.88
2021-01-05,ICI EU SIVEMI,99.25999999999999
2021-01-05,IEPISMI,676.2
2021-01-05,ILAVI,88.81
2021-01-05,IMICIPRA,119.9
2021-01-05,IMLAIZA,153.89000000000001
2021-01-05,IMRISFURI SPIRM MUMRAMAIM,780.0
2021-01-05,IPALUPAES,1475.3
2021-01-05,IPUPIEMAI,9410.550000000001
2021-01-05,IRIR OIS PUOUMIS,590.3299999999999
2021-01-05,ISIM,1154.3899999999999
2021-01-05,ISIM O RIRARIRA,1056.5
2021-01-05,IUMPICA,47910.35
2021-01-05,IVIMAR,94.0
2021-01-05,LIFM,389.9
2021-01-05,LILI CISRUMACS,19.9
2021-01-05,LIS RUS,176.0
2021-01-05,LIS URPIMIOUS,120.5
2021-01-05,LU PUMAM RICIRIMS,20.0
2021-01-05,LUCITA,457.84999999999997
2021-01-05,LUI CISRUMACIS,111.4
2021-01-05,LUPI,139.2
2021-01-05,LUPIMUIM,1977.1899999999998
2021-01-05,LUVAES,109.9
2021-01-05,MATATA,10.0
2021-01-05,MICI PULA,264.2
2021-01-05,MIMAMI SAMU VAMUIGU,135.0
2021-01-05,MIZPIZ,59.1
2021-01-05,MOIRI MPECILIMU PIR,37.4
2021-01-05,MRIMUIRAI,119.0
2021-01-05,MRIRI LIP,277.8
2021-01-05,MRUS GIROUS,58.0
2021-01-05,MU PURGAR,308.0
2021-01-05,MUMRIFAM,4419.46
2021-01-05,MUMUO PIVIRAIM,143.33
2021-01-05,MURPURI OUS GURAIS,1037.7
2021-01-05,MZU PIEO SZIP,1281.22
2021-01-05,MZU PLICA PAF,130.0
2021-01-05,MZU SMUIG FICMIRO,69.8
2021-01-05,MZU SUACU LIP,194.07
2021-01-05,OIGIPUARO,900.0
2021-01-05,PALLO MZU GRALA,2885.5
2021-01-05,PALLO PURGAR,117.1
2021-01-05,PAPA SUCIS,11532.119999999999
2021-01-05,PASCIAMO,116.0
2021-01-05,PASCIAMU,62.9
2021-01-05,PAZZI PIRPACO,864.0
2021-01-05,PAZZI ZUM,3266.11
2021-01-05,PEC PILIS,23.0
2021-01-05,PEUIM GAMTRAM,209.2
2021-01-05,PF PIR FIVIR,342.29999999999995
2021-01-05,PIARO,1057.64
2021-01-05,PIGUE PIPACO,5040.7
2021-01-05,PILIOU RAS,1564.9
2021-01-05,PIMGUCIS DA VIVA,769.3
2021-01-05,PIMRIMA,990.1999999999999
2021-01-05,PIPCIRM GIUARUM,58.4
2021-01-05,PIPRU SUIM,681.08
2021-01-05,PIPS,453.7
2021-01-05,PIRAGUAM,165.0
2021-01-05,PIRMI DA SIPIR,246.2
2021-01-05,PIULIMGURAU CIRAICI,108.25
2021-01-05,PRIMIUVI,35.0
2021-01-05,PRIMZURS RUSMIURIMA U PAZZIRAI,94.0
2021-01-05,PRISEMCICIU,185.0
2021-01-05,PRISMAURAI,167.99
2021-01-05,PUGUM,159.9
2021-01-05,PULGAIM SIOLLU,54.8
2021-01-05,PUMGUA,177.0
2021-01-05,PUPALU GALA,40.98
2021-01-05,PUPALU RAS,47.5
2021-01-05,PUPALU RAS MUI,36.0
2021-01-05,PUPALUGALA,73.97999999999999
2021-01-05,RAMZI CISMURUARI RA SIPIMUARI,45.0
2021-01-05,RASMUR S,1803.9
2021-01-05,RC OUMILEES,3119.8
2021-01-05,RIARI SIARI,114.0
2021-01-05,RIC IME CZASU,472.09999999999997
2021-01-05,RIGU I CIGU,35.9
2021-01-05,RIMAI EU TRAPRISCI,1338.4
2021-01-05,RIRAI CISAMZI,57.8
2021-01-05,RIRIMI,63.41
2021-01-05,RIRURPIS,697.55
2021-01-05,RISA PUM,58.0
2021-01-05,RISIRA,530.0
2021-01-05,RIVUMOI MRIMUIRAI,302.3
2021-01-05,RIZIGIMO,54.9
2021-01-05,RO PISMUAS,2019.0
2021-01-05,RUA DA RIMU,72.1
2021-01-05,RUGI SMIRU CICIU SZIS,74.9
2021-01-05,RUMOU VUREU,236.0
2021-01-05,RUSU,1132.2
2021-01-05,SALITO,662.6
2021-01-05,SIRVUMU AMILAI,708.3000000000001
2021-01-05,SIZMUO RICAUMS,1560.0
2021-01-05,SPILUMI,1989.77
2021-01-05,SR SIGIRIMI,1760.5
2021-01-05,SUCOI LIMTRAS,76.5
2021-01-05,SUMIR SIMMPE,35.9
2021-01-05,SUPSIO,2433.5299999999997
2021-01-05,SUPUR GRALA,80.69999999999999
2021-01-05,SUSM GRALA,51.9
2021-01-05,SUSZAIGA,1732.8999999999999
2021-01-05,TRAF VURGO,58.8
2021-01-05,TRAZ LOURA RIRMAM,191.0
2021-01-05,USMIMOI RS,26.9
2021-01-05,USPUMUI CIRAICI,399.75
2021-01-05,VALLUES CIOLA E CIGU CIE,38.0
2021-01-05,VUG U LUV,410.0
2021-01-05,VUG UP,737.7
2021-01-05,ZIM M MUMEUR,782.3
2021-01-05,ZIM ME MUMEUR,138.41
2021-01-05,ZIMRPI,0.0
2021-01-05,ZIRIE,186.9
2021-01-05,ZIVIAIMIS,39.99
2021-01-05,ZIVIMUI,260.3
2021-01-05,ZIZULO,125.0
2021-01-06,AIEMAMIMU IU PRUSEM,308.0
2021-01-06,AR FAM,23.4
2021-01-06,AR PAZZI,299.79999999999995
2021-01-06,AR TRAMUO,252.3
2021-01-06,ARE TRAMUO,1063.9
2021-01-06,CICIU SZIS,161.15
2021-01-06,CILAFIRMAI CIOLA,342.29
2021-01-06,CIMUAMI PUIMISURI,140.7